sonar.projectKey=KevinCarrillo031_CalidadSoftware
sonar.organization=kevincarrillo031
sonar.projectName=CalidadSoftware
sonar.projectVersion=1.0

# Indica dónde están los archivos fuente
sonar.sources=.

# Forzar que tome archivos .R como texto
sonar.inclusions=**/*.R

# Configura la codificación
sonar.sourceEncoding=UTF-8
